name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install --no-shrinkwrap eslint
        run: npm install --no-shrinkwrap eslint
      - name: npm install @typescript-eslint/eslint-plugin@latest --save-dev
        run: npm install @typescript-eslint/eslint-plugin@latest --save-dev
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: './'
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          locale: "US"
